"""empty message

Revision ID: 07d316a4e527
Revises: ed80b92996c5
Create Date: 2018-10-22 15:22:32.176907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07d316a4e527'
down_revision = 'ed80b92996c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('area', sa.String(length=200), nullable=False),
    sa.Column('salary', sa.String(length=200), nullable=False),
    sa.Column('publishdate', sa.String(length=200), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
