"""empty message

Revision ID: 549a6e9aabcc
Revises: 1905e4d776f5
Create Date: 2018-08-23 16:30:41.200818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549a6e9aabcc'
down_revision = '1905e4d776f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=False),
    sa.Column('modifytime', sa.DateTime(), nullable=False),
    sa.Column('createtime', sa.DateTime(), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('internalname', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('internalname'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
