"""empty message

Revision ID: d4b2a50001f8
Revises: 07d316a4e527
Create Date: 2018-10-22 15:58:56.652852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4b2a50001f8'
down_revision = '07d316a4e527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('downloaddate', sa.DateTime(), nullable=False))
    op.alter_column('jobs', 'salary',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'salary',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.drop_column('jobs', 'downloaddate')
    # ### end Alembic commands ###
