"""empty message

Revision ID: ed80b92996c5
Revises: 549a6e9aabcc
Create Date: 2018-08-29 17:49:48.226347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed80b92996c5'
down_revision = '549a6e9aabcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('moduleid', sa.String(length=10), nullable=False),
    sa.Column('modulename', sa.String(length=30), nullable=True),
    sa.Column('moduleicontype', sa.String(length=10), nullable=True),
    sa.Column('moduleurl', sa.String(length=200), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('moduleid'),
    sa.UniqueConstraint('modulename'),
    sa.UniqueConstraint('moduleurl')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modules')
    # ### end Alembic commands ###
